const data = {
  appointments: [
    {
      firstName: "Anita",
      lastName: "Shrestha",
      email: "anita.shrestha@example.com",
      phone: "9812345678",
      service: "Ovulation induction",
      counselling: "In clinic",
      city: "Damak",
      date: "2025-09-20",
      time: "09:00 AM",
      referral: "Social Media",
      message: "First consultation for fertility checkup."
    },
    {
      firstName: "Ramesh",
      lastName: "Karki",
      email: "ramesh.karki@example.com",
      phone: "9801122334",
      service: "Intrauterine Insemination (IUI)",
      counselling: "Online",
      city: "Birtamode",
      date: "2025-09-21",
      time: "11:00 AM",
      referral: "Google Search",
      message: "Need advice on IUI treatment options."
    },
    {
      firstName: "Sita",
      lastName: "Rai",
      email: "sita.rai@example.com",
      phone: "9867788990",
      service: "Antenatal Checkup",
      counselling: "In clinic",
      city: "Dharan",
      date: "2025-09-22",
      time: "10:30 AM",
      referral: "FM Radio",
      message: "Regular antenatal visit for 2nd trimester."
    },
    {
      firstName: "Kiran",
      lastName: "Mishra",
      email: "kiran.mishra@example.com",
      phone: "9845566778",
      service: "Endometriosis Treatment",
      counselling: "In clinic",
      city: "Itahari",
      date: "2025-09-23",
      time: "02:00 PM",
      referral: "Website",
      message: "Follow-up after ultrasound diagnosis."
    },
    {
      firstName: "Maya",
      lastName: "Tamang",
      email: "maya.tamang@example.com",
      phone: "9811223344",
      service: "Polycystic Ovary Syndrome (PCOD)",
      counselling: "Online",
      city: "Urlabari",
      date: "2025-09-24",
      time: "04:00 PM",
      referral: "Social Media",
      message: "Wants to discuss PCOD treatment plan."
    },
    {
      firstName: "Sunil",
      lastName: "Adhikari",
      email: "sunil.adhikari@example.com",
      phone: "9823456789",
      service: "Menstrual Irregularities",
      counselling: "In clinic",
      city: "Inaruwa",
      date: "2025-09-25",
      time: "03:00 PM",
      referral: "Wall Poster",
      message: "Booking appointment for my wife’s irregular cycles."
    },
    {
      firstName: "Puja",
      lastName: "Basnet",
      email: "puja.basnet@example.com",
      phone: "9804455667",
      service: "Ovarian Cysts",
      counselling: "In clinic",
      city: "Other",
      date: "2025-09-26",
      time: "11:30 AM",
      referral: "Blog",
      message: "Ultrasound detected cyst, need further evaluation."
    },
    {
      firstName: "Rajesh",
      lastName: "Gurung",
      email: "rajesh.gurung@example.com",
      phone: "9845566123",
      service: "Uterine Fibroids",
      counselling: "Online",
      city: "Damak",
      date: "2025-09-26",
      time: "05:00 PM",
      referral: "Hoarding Board",
      message: "Second opinion on fibroid treatment."
    },
    {
      firstName: "Anju",
      lastName: "KC",
      email: "anju.kc@example.com",
      phone: "9809988776",
      service: "Adenomyosis",
      counselling: "In clinic",
      city: "Dharan",
      date: "2025-09-26",
      time: "09:30 AM",
      referral: "Google Search",
      message: "Severe menstrual pain, looking for treatment."
    },
    {
      firstName: "Manish",
      lastName: "Shah",
      email: "manish.shah@example.com",
      phone: "9813344556",
      service: "Pelvic Inflammatory Disease (PID)",
      counselling: "Online",
      city: "Itahari",
      date: "2025-09-26",
      time: "06:00 PM",
      referral: "Other Medium",
      message: "Need consultation for recurring infection."
    },

    // 🔽 Extra 10 Appointments
    {
      firstName: "Bikash",
      lastName: "Thapa",
      email: "bikash.thapa@example.com",
      phone: "9801239876",
      service: "Male Infertility",
      counselling: "In clinic",
      city: "Biratnagar",
      date: "2025-09-30",
      time: "10:00 AM",
      referral: "Friend",
      message: "Consultation for low sperm count issues."
    },
    {
      firstName: "Deepa",
      lastName: "Magar",
      email: "deepa.magar@example.com",
      phone: "9845567890",
      service: "Menopause Management",
      counselling: "Online",
      city: "Jhapa",
      date: "2025-10-01",
      time: "12:30 PM",
      referral: "Facebook",
      message: "Looking for hormone therapy consultation."
    },
    {
      firstName: "Rohit",
      lastName: "Jha",
      email: "rohit.jha@example.com",
      phone: "9812233445",
      service: "Contraception Counseling",
      counselling: "In clinic",
      city: "Birgunj",
      date: "2025-10-02",
      time: "02:15 PM",
      referral: "Poster",
      message: "Need advice on permanent contraception methods."
    },
    {
      firstName: "Nirmala",
      lastName: "Shah",
      email: "nirmala.shah@example.com",
      phone: "9807788990",
      service: "Fertility Preservation",
      counselling: "In clinic",
      city: "Kathmandu",
      date: "2025-10-03",
      time: "09:45 AM",
      referral: "Google Search",
      message: "Wants to freeze eggs for future family planning."
    },
    {
      firstName: "Prakash",
      lastName: "Yadav",
      email: "prakash.yadav@example.com",
      phone: "9861122334",
      service: "Genetic Counseling",
      counselling: "Online",
      city: "Janakpur",
      date: "2025-10-04",
      time: "03:30 PM",
      referral: "Hospital Staff",
      message: "Family history of genetic disorders, seeking guidance."
    },
    {
      firstName: "Sabina",
      lastName: "Shrestha",
      email: "sabina.shrestha@example.com",
      phone: "9818899007",
      service: "Pregnancy Test",
      counselling: "In clinic",
      city: "Pokhara",
      date: "2025-10-05",
      time: "11:00 AM",
      referral: "Radio Ad",
      message: "Came for confirmation of pregnancy."
    },
    {
      firstName: "Arjun",
      lastName: "Lama",
      email: "arjun.lama@example.com",
      phone: "9802233445",
      service: "Vaginal Infections",
      counselling: "In clinic",
      city: "Lalitpur",
      date: "2025-10-06",
      time: "01:00 PM",
      referral: "Relative",
      message: "Recurring infection issues, needs treatment."
    },
    {
      firstName: "Kusum",
      lastName: "Bhandari",
      email: "kusum.bhandari@example.com",
      phone: "9823344556",
      service: "Pregnancy Ultrasound",
      counselling: "Online",
      city: "Chitwan",
      date: "2025-10-07",
      time: "04:30 PM",
      referral: "Doctor Referral",
      message: "Second trimester ultrasound booking."
    },
    {
      firstName: "Sanjay",
      lastName: "Gupta",
      email: "sanjay.gupta@example.com",
      phone: "9813344789",
      service: "IVF Consultation",
      counselling: "In clinic",
      city: "Biratnagar",
      date: "2025-10-08",
      time: "05:15 PM",
      referral: "Internet",
      message: "Discuss IVF success rates and cost."
    },
    {
      firstName: "Laxmi",
      lastName: "Karki",
      email: "laxmi.karki@example.com",
      phone: "9805566778",
      service: "Recurrent Miscarriages",
      counselling: "In clinic",
      city: "Bharatpur",
      date: "2025-10-09",
      time: "09:00 AM",
      referral: "NGO",
      message: "Looking for treatment after multiple miscarriages."
    }
  ]
};

module.exports = data;
